# Min Light — ultra-minimal VS Code theme
# github.com/misolori/min-theme

bg = "#FFFFFF"
bg_light = "#F0F0F0"
fg = "#1B1B1B"
fg_dim = "#B0B0B0"

red = "#D44950"
green = "#61862F"
yellow = "#B6A243"
blue = "#4E76A1"
magenta = "#A353AC"
cyan = "#399BA7"
orange = "#D78051"

border_active = "blue"
border_inactive = "#D0D0D0"
status_bg = "#E5E5E5"
cursor_line = "#E8E8E8"

dir_color = "blue"
symlink_color = "cyan"
file_color = "fg"
